---
title: "Computing assignment 2"
author: "Alyssa Vanderbeek"
date: "21 October 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
```

## Problem 1

```{r 3plus3_function}
# p.true = vector of true DLT probabilities for each test dose
# n.dose = number (integer) of test doses
# N = number of simulations to run
performance_3plus3 <- function(p.true, n.dose, N){
  results = vector(mode = "list", length = N)
  
  for (sim in 1:N) {
    pt = 1 # patient on dose k
    n = 1 # patient on trial
    dose = 1 # dose k
    esc = 1 # escalation yes/no
    mtd = 0 # MTD
    
    dlts = vector(mode = 'list', length = n.dose)
    
    while (esc == 1 && dose <= n.dose && pt <= 6) {
      dlts[[dose]][pt] = rbinom(1, 1, p.true[dose])
      
      # If <3 pts enrolled on current dose, enroll next pt on same dose
      if (length(dlts[[dose]]) < 3) {
        pt = pt + 1
        n = n + 1
        dose = dose
        # If 1/3 pts on current dose observe DLT, enroll next 3 patients on same dose
      } else if (sum(dlts[[dose]]) == 1 && length(dlts[[dose]]) == 3) {
        pt = pt + 1
        n = n + 1
        dose = dose
        # If 0/3 pts on current dose observe DLT, escalate dose
      } else if (sum(dlts[[dose]]) == 0 && length(dlts[[dose]]) == 3) {
        pt = 1
        mtd = dose
        dose = dose + 1
        n = n + 1
        # If <=1 patient out of 3-6 observe DLT, stay at same dose
      } else if (sum(dlts[[dose]]) <= 1 && length(dlts[[dose]]) > 3 && length(dlts[[dose]]) < 6) {
        pt = pt + 1
        n = n + 1
        mtd = dose
        dose = dose
        # If we observe 0/6 DLT, escalate dose
      } else if (sum(dlts[[dose]]) == 0 && length(dlts[[dose]]) == 6) {
        pt = 1
        n = n + 1
        mtd = dose
        dose = dose + 1
        # If we observe 1/6 DLTs, stop escalation and declare this dose level the MTD
      } else if (sum(dlts[[dose]]) == 1 && length(dlts[[dose]]) == 6) {
        esc = 0 # MTD
        mtd = dose
        # If we observe 2 DLTs at the current dose level, stop the trial and declare the previous dose the MTD
      } else if (sum(dlts[[dose]]) > 1) {
        esc = 0 
        mtd = dose - 1
      } else {
        dlts[[dose]][pt] = NA # reassign entry as NA in case of error
      }
    }
    
    results[[sim]] = list(dlts = unlist(lapply(dlts, sum)),
                          nperdose = unlist(lapply(dlts, length)),
                          n = n,
                          mtd = mtd)
  }
  return(results)
}
```


```{r p1}
p.true1 = c(0.017, 0.043, 0.10, 0.22, 0.41)
n.dose = 5
N = 1e3

set.seed(1)
sims = performance_3plus3(p.true1, n.dose, N)

n.dlts = do.call(rbind, lapply(sims, `[[`, 1))
n.pts = do.call(rbind, lapply(sims, `[[`, 2))
mtd.1 = unlist(lapply(sims, `[[`, 4))


## Table of performance metrics
rbind(p.true1,
      table(mtd.1)[-1]/N,
      colMeans(n.pts),
      colMeans(n.dlts)) %>%
  `rownames<-`(c("True DLT probability",
                             "Selection probability",
                             "Avg number of patients treated",
                             "Avg number of patients with DLT")) %>%
  knitr::kable(row.names = TRUE)
```


## Problem 2

```{r 2a}
p.true2 = c(0.10, 0.22, 0.41, 0.64, 0.81)
n.dose = 5
N = 1000

set.seed(1)
sims = performance_3plus3(p.true2, n.dose, N)

n.dlts = do.call(rbind, lapply(sims, `[[`, 1))
n.pts = do.call(rbind, lapply(sims, `[[`, 2))
mtd.1 = unlist(lapply(sims, `[[`, 4))

mtd.selection = table(mtd.1[which(mtd.1 != 0)])/N
if (length(mtd.selection) < 5) {
  r = 5 - length(mtd.selection)
  mtd.selection = c(mtd.selection, rep(0, r))
}

## Table of performance metrics
rbind(p.true2,
      mtd.selection,
      colMeans(n.pts),
      colMeans(n.dlts)) %>%
  `rownames<-`(c("True DLT probability",
                 "Selection probability",
                 "Avg number of patients treated",
                 "Avg number of patients with DLT")) %>%
  `colnames<-`(1:n.dose) %>%
  knitr::kable(row.names = TRUE,
               caption = "Performance metrics for 3+3 design when true DLT rates are p=0.10, 0.22, 0.41, 0.64, 0.81")
```

```{r 2b}
p.true3 = c(0.043, 0.10, 0.22, 0.41, 0.64)
n.dose = 5
N = 1000

set.seed(1)
sims = performance_3plus3(p.true3, n.dose, N)

n.dlts = do.call(rbind, lapply(sims, `[[`, 1))
n.pts = do.call(rbind, lapply(sims, `[[`, 2))
mtd.1 = unlist(lapply(sims, `[[`, 4))

mtd.selection = table(mtd.1[which(mtd.1 != 0)])/N
if (length(mtd.selection) < 5) {
  r = 5 - length(mtd.selection)
  mtd.selection = c(mtd.selection, rep(0, r))
}

## Table of performance metrics
rbind(p.true3,
      mtd.selection,
      colMeans(n.pts),
      colMeans(n.dlts)) %>%
  `rownames<-`(c("True DLT probability",
                 "Selection probability",
                 "Avg number of patients treated",
                 "Avg number of patients with DLT")) %>%
  `colnames<-`(1:n.dose) %>%
  knitr::kable(row.names = TRUE,
               caption = "Performance metrics for 3+3 design when true DLT rates are p=0.043, 0.10, 0.22, 0.41, 0.64")
```


```{r 2c}
p.true4 = c(0.007, 0.017, 0.043, 0.10, 0.22)
n.dose = 5
N = 1000

set.seed(1)
sims = performance_3plus3(p.true4, n.dose, N)

n.dlts = do.call(rbind, lapply(sims, `[[`, 1))
n.pts = do.call(rbind, lapply(sims, `[[`, 2))
mtd.1 = unlist(lapply(sims, `[[`, 4))

mtd.selection = table(mtd.1[which(mtd.1 != 0)])/N
if (length(mtd.selection) < 5) {
  r = 5 - length(mtd.selection)
  mtd.selection = c(mtd.selection, rep(0, r))
}

## Table of performance metrics
rbind(p.true4,
      mtd.selection,
      colMeans(n.pts),
      colMeans(n.dlts)) %>%
  `rownames<-`(c("True DLT probability",
                 "Selection probability",
                 "Avg number of patients treated",
                 "Avg number of patients with DLT")) %>%
  `colnames<-`(1:n.dose) %>%
  knitr::kable(row.names = TRUE,
               caption = "Performance metrics for 3+3 design when true DLT rates are p=0.007, 0.017, 0.043, 0.10, 0.22")
```



```{r 2d}
p.true5 = c(0.003, 0.007, 0.017, 0.043, 0.10)
n.dose = 5
N = 1000

set.seed(1)
sims = performance_3plus3(p.true5, n.dose, N)

n.dlts = do.call(rbind, lapply(sims, `[[`, 1))
n.pts = do.call(rbind, lapply(sims, `[[`, 2))
mtd.1 = unlist(lapply(sims, `[[`, 4))

mtd.selection = table(mtd.1[which(mtd.1 != 0)])/N
if (length(mtd.selection) < 5) {
  r = 5 - length(mtd.selection)
  mtd.selection = c(mtd.selection, rep(0, r))
}

## Table of performance metrics
rbind(p.true5,
      mtd.selection,
      colMeans(n.pts),
      colMeans(n.dlts)) %>%
  `rownames<-`(c("True DLT probability",
                 "Selection probability",
                 "Avg number of patients treated",
                 "Avg number of patients with DLT")) %>%
  `colnames<-`(1:n.dose) %>%
  knitr::kable(row.names = TRUE,
               caption = "Performance metrics for 3+3 design when true DLT rates are p=0.003, 0.007, 0.017, 0.043, 0.10")
```


## Problem 3

```{r crm}
library(dfcrm)

N = 100
n = 31
p = 0.1
tru1 = which(p.true1 == p)

p01 = getprior(halfwidth = 0.06, target = p, nu = tru1, nlevel = n.dose); p01
simfit1 = crmsim(p.true1, prior = p01, target = p, n = n, x0 = 3, nsim = N)
plot(simfit1)
simfit1$MTD



tru2 = which(p.true2 == p)

p02 = getprior(halfwidth = 0.06, target = p, nu = tru2, nlevel = n.dose); p02
simfit2 = crmsim(p.true2, prior = p02, target = p, n = n, x0 = 3, nsim = N)
plot(simfit2)
simfit2$MTD



tru3 = which(p.true3 == p)

p03 = getprior(halfwidth = 0.06, target = p, nu = tru3, nlevel = n.dose); p03
simfit3 = crmsim(p.true3, prior = p03, target = p, n = n, x0 = 3, nsim = N)
plot(simfit3)
simfit3$MTD



tru4 = which(p.true4 == p)

p04 = getprior(halfwidth = 0.06, target = p, nu = tru4, nlevel = n.dose); p04
simfit4 = crmsim(p.true4, prior = p04, target = p, n = n, x0 = 3, nsim = N)
plot(simfit4)
simfit4$MTD




tru5 = which(p.true5 == p)

p05 = getprior(halfwidth = 0.06, target = p, nu = tru5, nlevel = n.dose); p05
simfit5 = crmsim(p.true5, prior = p01, target = p, n = n, x0 = 3, nsim = N)
plot(simfit5)
simfit5$MTD


```


```{r crm_metrics}

## Table of performance metrics
rbind(p.true1,
      simfit1$MTD,
      simfit1$level,
      simfit1$tox) %>%
  `rownames<-`(c("True DLT probability",
                 "Selection probability",
                 "Avg number of patients treated",
                 "Avg number of patients with DLT")) %>%
  `colnames<-`(1:n.dose) %>%
  knitr::kable(row.names = TRUE,
               caption = "Performance metrics for 3+3 design when true DLT rates are p=0.017, 0.043, 0.10, 0.22, 0.41")

## Table of performance metrics
rbind(p.true2,
      simfit2$MTD,
      simfit2$level,
      simfit2$tox) %>%
  `rownames<-`(c("True DLT probability",
                 "Selection probability",
                 "Avg number of patients treated",
                 "Avg number of patients with DLT")) %>%
  `colnames<-`(1:n.dose) %>%
  knitr::kable(row.names = TRUE,
               caption = "Performance metrics for 3+3 design when true DLT rates are p=0.10, 0.22, 0.41, 0.64, 0.81")

## Table of performance metrics
rbind(p.true3,
      simfit3$MTD,
      simfit3$level,
      simfit3$tox) %>%
  `rownames<-`(c("True DLT probability",
                 "Selection probability",
                 "Avg number of patients treated",
                 "Avg number of patients with DLT")) %>%
  `colnames<-`(1:n.dose) %>%
  knitr::kable(row.names = TRUE,
               caption = "Performance metrics for 3+3 design when true DLT rates are p=0.043, 0.10, 0.22, 0.41, 0.64")

## Table of performance metrics
rbind(p.true4,
      simfit4$MTD,
      simfit4$level,
      simfit4$tox) %>%
  `rownames<-`(c("True DLT probability",
                 "Selection probability",
                 "Avg number of patients treated",
                 "Avg number of patients with DLT")) %>%
  `colnames<-`(1:n.dose) %>%
  knitr::kable(row.names = TRUE,
               caption = "Performance metrics for 3+3 design when true DLT rates are p=0.007, 0.017, 0.043, 0.10, 0.22")

## Table of performance metrics
rbind(p.true5,
      simfit5$MTD,
      simfit5$level,
      simfit5$tox) %>%
  `rownames<-`(c("True DLT probability",
                 "Selection probability",
                 "Avg number of patients treated",
                 "Avg number of patients with DLT")) %>%
  `colnames<-`(1:n.dose) %>%
  knitr::kable(row.names = TRUE,
               caption = "Performance metrics for 3+3 design when true DLT rates are p=0.003, 0.007, 0.017, 0.043, 0.10")



avg.PCS = mean(c(simfit1$MTD[tru1],
                 simfit2$MTD[tru2],
                 simfit3$MTD[tru3],
                 simfit4$MTD[tru4],
                 simfit5$MTD[tru5]))
avg.PCS
```